### ISSUE TITLE
NullPointerException in FindTouchPointsMethodAdapter.visitLineNumber

### ISSUE THREAD

**Issue by oosterholt** [cobertura/cobertura#200]
Some of our classes throw NullPointerExceptions when cobertura tries to instrument those.
This is the stacktrace:

    [cobertura-instrument] WARN   instrumentClass, Unable to instrument file /home/jenkins/jobs/Test Coverage/workspace/build/classes/path/to/package/AClass.class
    [cobertura-instrument] java.lang.NullPointerException
    [cobertura-instrument] 	at java.util.LinkedList.addAll(LinkedList.java:269)
    [cobertura-instrument] 	at java.util.LinkedList.addAll(LinkedList.java:247)
    [cobertura-instrument] 	at java.util.LinkedList.<init>(LinkedList.java:98)
    [cobertura-instrument] 	at net.sourceforge.cobertura.instrument.FindTouchPointsMethodAdapter.visitLineNumber(FindTouchPointsMethodAdapter.java:196)
    [cobertura-instrument] 	at org.objectweb.asm.ClassReader.a(Unknown Source)
    [cobertura-instrument] 	at org.objectweb.asm.ClassReader.b(Unknown Source)
    [cobertura-instrument] 	at org.objectweb.asm.ClassReader.accept(Unknown Source)
    [cobertura-instrument] 	at org.objectweb.asm.ClassReader.accept(Unknown Source)
    [cobertura-instrument] 	at net.sourceforge.cobertura.instrument.CoberturaInstrumenter.instrumentClass(CoberturaInstrumenter.java:161)
    [cobertura-instrument] 	at net.sourceforge.cobertura.instrument.CoberturaInstrumenter.instrumentClass(CoberturaInstrumenter.java:121)
    [cobertura-instrument] 	at net.sourceforge.cobertura.instrument.CoberturaInstrumenter.addInstrumentationToSingleClass(CoberturaInstrumenter.java:234)
    [cobertura-instrument] 	at net.sourceforge.cobertura.instrument.Main.addInstrumentationToSingleClass(Main.java:298)
    [cobertura-instrument] 	at net.sourceforge.cobertura.instrument.Main.addInstrumentation(Main.java:307)
    [cobertura-instrument] 	at net.sourceforge.cobertura.instrument.Main.parseArguments(Main.java:399)
    [cobertura-instrument] 	at net.sourceforge.cobertura.instrument.Main.main(Main.java:421)

We are using Cobertura 2.0.3 and we instrument the classes using the ant task.

When more info is needed, I'm happy to provide it.

**Comment by oosterholt** [comment]
Issue is still reproducible in latest release ([cobertura-2.1.1](https://github.com/cobertura/cobertura/releases/tag/cobertura-2.1.1)).

**Comment by knicholes** [comment]
I'm getting this problem as well.

**Comment by sirlatrom** [comment]
Still seeing this in [cobertura-2.1.1] (https://github.com/cobertura/cobertura/releases/tag/cobertura-2.1.1), and I would like to know if there is any way I can help to fix the issue.

**Comment by TheNitek** [comment]
Did anyone find another workaround than removing the ignoreTrivial?

**Comment by crc83** [comment]
I got this issue for single class with empty private constructor. I've removed it and all went fine

**Comment by christ66** [comment]
Fixed in 70022c1

**Comment by bamcgill** [comment]
looks like this is still happening in 2.1.1 with ant task. Removing ignore trivial cleans up the instrumentation.....

**Comment by heydev** [comment]
I'm also seeing this in the Maven Cobertura plugin 2.7. Setting ignoreTrivial to false gets around the issue.

**Comment by milkotodorov** [comment]
Still occurring with Maven Cobertura plugin 2.7...
